name: Security & Code Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build Node App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build || true

      - name: Build Docker image
        run: docker build -t puzzle-todo-vulnerable:latest .

      - name: Save Docker image
        run: docker save puzzle-todo-vulnerable:latest -o puzzle-todo-vulnerable.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: puzzle-todo-vulnerable-image
          path: puzzle-todo-vulnerable.tar

  sonar_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=BagasDhitya_puzzle-todo-vulnerable
            -Dsonar.organization=bagasdhitya
            -Dsonar.sources=src
        env:
          SONAR_TOKEN: ${{ secrets.MY_SONAR_TOKEN }}

      - name: Upload SonarQube Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: puzzle-todo-vulnerable-sonar-report
          path: .scannerwork

  docker_build_and_scan:
    name: Docker Trivy Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: puzzle-todo-vulnerable-image

      - name: Load Docker image
        run: docker load -i puzzle-todo-vulnerable.tar

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: "puzzle-todo-vulnerable:latest"

      - name: Filesystem Scan with Trivy
        uses: aquasecurity/trivy-action@0.31.0
        with:
          scan-type: fs
          dir: .
          format: json
          output: puzzle-todo-vulnerable-trivy-fs-report.json

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: puzzle-todo-vulnerable-trivy-reports
          path: puzzle-todo-vulnerable-trivy-fs-report.json

  zap_scan:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: puzzle-todo-vulnerable-image

      - name: Load Docker image
        run: docker load -i puzzle-todo-vulnerable.tar

      - name: Run app container
        run: |
          docker run -d -p 3000:3000 --name puzzle-todo-app puzzle-todo-vulnerable:latest
          sleep 15

      - name: Prepare zap-reports folder
        run: mkdir -p zap-reports

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:3000"
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          cmd_options: >
            --autooff
            -r zap-reports/zap-report.html
            -J zap-reports/zap-report.json
            -w zap-reports/zap-report.md

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: puzzle-todo-vulnerable-zap-reports
          path: zap-reports
